// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWWMJl-4z3XHhSbIPwcKXs1Ml4kqSAaIA',
    appId: '1:248318585219:web:22cf592e4d462610f46eb6',
    messagingSenderId: '248318585219',
    projectId: 'notification-c560b',
    authDomain: 'notification-c560b.firebaseapp.com',
    storageBucket: 'notification-c560b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdFfScQAIcQJBOtxEcaTkGOdpjmiNxVQ',
    appId: '1:248318585219:android:2c1baa7bf9fb4061f46eb6',
    messagingSenderId: '248318585219',
    projectId: 'notification-c560b',
    storageBucket: 'notification-c560b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3P8bq3D2Xw2nzoHUR8ATovNrnDZSdmY',
    appId: '1:248318585219:ios:fb7b6977e406ecd9f46eb6',
    messagingSenderId: '248318585219',
    projectId: 'notification-c560b',
    storageBucket: 'notification-c560b.appspot.com',
    iosBundleId: 'com.example.ssrac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3P8bq3D2Xw2nzoHUR8ATovNrnDZSdmY',
    appId: '1:248318585219:ios:52bcfe5745be27a1f46eb6',
    messagingSenderId: '248318585219',
    projectId: 'notification-c560b',
    storageBucket: 'notification-c560b.appspot.com',
    iosBundleId: 'com.example.modern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWWMJl-4z3XHhSbIPwcKXs1Ml4kqSAaIA',
    appId: '1:248318585219:web:de3f7f213b7674edf46eb6',
    messagingSenderId: '248318585219',
    projectId: 'notification-c560b',
    authDomain: 'notification-c560b.firebaseapp.com',
    storageBucket: 'notification-c560b.appspot.com',
  );
}
